{
 "title": "Nano Stats & Counters (+ Histograms V2)",
 "tags": [ "nano" ],
 "time": { "from": "2024-10-21T16:22:33.000Z", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(nano_block_count, job)"
    }
   },
   {
    "name": "Instance",
    "query": {
     "query": "label_values(nano_block_count{job='${Job}'}, instance)"
    }
   },
   {
    "name": "stats_type",
    "label": "Stats Counters",
    "query": {
     "query": "label_values(nano_stats_counters,type)"
    }
   },
   {
    "name": "stats_detail",
    "label": "Stats Details",
    "query": {
     "query": "label_values(nano_stats_counters,detail)"
    }
   },
   {
    "name": "stats_dir",
    "label": "Stats Direction",
    "query": {
     "query": "label_values(nano_stats_counters,dir)"
    }
   },
   {
    "name": "stats_objects_l1",
    "label": "Stats Objects",
    "query": {
     "query": "label_values(nano_stats_objects_count,l1)"
    }
   },
   { "name": "Blocks", "query": "cemented,count" },
   {
    "name": "message_type",
    "label": "Message Types",
    "query": {
     "query": "label_values(nano_stats_counters{type='message'},detail)"
    }
   },
   { "name": "Rate", "query": "1s, 5s, 15s, 30s, 60s" },
   { "name": "Step", "query": "1s, 3s, 5s, 10s, 15s, 30s, 60s" },
   {
    "name": "samples_detail",
    "label": "Samples",
    "query": {
     "query": "label_values(nano_stats_samples_count,sample)"
    }
   },
   {
    "name": "rpc_method",
    "label": "Rpc Method",
    "query": {
     "query": "label_values(nano_rpc_response_bucket, method)"
    }
   },
   {
    "name": "priority_bucket",
    "label": "Priority Bucket",
    "query": {
     "query": "label_values(nano_confirmation_history_hist_bucket,priority_bucket)"
    }
   },
   {
    "name": "samples_vote_detail",
    "label": "Samples",
    "query": {
     "query": "label_values(nano_stats_samples_votes_count, sample)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Last Update",
     "type": "timeseries",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - push_time_seconds{job='${Job}', instance=~'${Instance}'}",
       "legendFormat": "[ {{instance}} ]"
      }
     ]
    },
    {
     "title": "Peer Count",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "nano_node_peer_count{job='${Job}', instance=~'${Instance}'}",
       "legendFormat": "[ {{instance}} ]"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "${message_type}/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
     "repeat": "message_type",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'message',dir=~'${stats_dir}',detail='${message_type}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{detail}} : {{dir}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Quorum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nano_node_online_stake_total{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] online stake"
      },
      {
       "expr": "nano_node_peers_stake_total{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] peer stake"
      },
      {
       "expr": "nano_node_quorum_delta{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] quorum"
      },
      {
       "expr": "nano_node_trended_stake_total{job='${Job}', instance=~'${Instance}'} / 10^30",
       "legendFormat": "[ {{instance}} ] trended stake"
      }
     ]
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "nano_block_count{job='${Job}', instance=~'${Instance}', type=~'${Blocks}'}",
     "legendFormat": "[ {{instance}} ] {{type}}"
    }
   ]
  },
  {
   "title": "Blocks/s (over ${Rate})",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nano_block_count{job='${Job}', instance=~'${Instance}', type=~'${Blocks}'}[${Rate}])",
     "legendFormat": "[ {{instance}} ] {{type}}"
    }
   ]
  },
  {
   "title": "Confirmation History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Confirmation History",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "nano_confirmation_history_stats{job='${Job}', instance=~'${Instance}', type='average'}",
       "legendFormat": "[{{instance}}] {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Counter Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_type}/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "repeat": "stats_type",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'${stats_type}',dir=~'${stats_dir}',detail=~'${stats_detail}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{detail}} : {{dir}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Counter Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_type}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "repeat": "stats_type",
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "nano_stats_counters{job='${Job}', instance=~'${Instance}',type=~'${stats_type}',dir=~'${stats_dir}'}",
       "legendFormat": "[ {{instance}} ] {{detail}} : {{dir}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "[ {{instance}} ] {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Count Rates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1}/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Active Elections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active [ALL]",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1=~'active',l2=~`blocks`}",
       "legendFormat": "[ {{instance}} ] {{l2}}"
      }
     ]
    },
    {
     "title": "Active Elections (max over $__interval) [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time(nano_stats_objects_count{job='${Job}', instance=~'${Instance}',l1='active',l2=~'normal|hinted|optimistic'}[$__interval])",
       "legendFormat": "[ {{instance}} ] {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Unchecked",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unchecked Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nano_block_count{job='${Job}', instance=~'${Instance}', type='unchecked'}",
       "legendFormat": "[ {{instance}} ] {{type}}"
      }
     ]
    },
    {
     "title": "Unchecked/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(nano_block_count{job='${Job}', instance=~'${Instance}', type=~'unchecked'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cemented",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cemented Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nano_block_count{job='${Job}', instance=~'${Instance}', type=~'cemented'}",
       "legendFormat": "[ {{instance}} ] {{type}}"
      }
     ]
    },
    {
     "title": "Cemented/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(nano_block_count{job='${Job}', instance=~'${Instance}', type=~'cemented'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Frontiers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Froniter Count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nano_node_frontier_count{job='${Job}', instance=~'${Instance}'}",
       "legendFormat": "[ {{instance}} ] frontiers"
      }
     ]
    },
    {
     "title": "Frontiers/s (over ${Rate})",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(nano_node_frontier_count{job='${Job}', instance=~'${Instance}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] frontiers"
      }
     ]
    }
   ]
  },
  {
   "title": "TX/RX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "TX/RX/s (over ${Rate}) [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(network_raw_tx{job='${Job}', instance=~'${Instance}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] send"
      },
      {
       "expr": "rate(network_raw_rx{job='${Job}', instance=~'${Instance}'}[${Rate}])",
       "legendFormat": "[ {{instance}} ] receive"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Threads (avg over $__interval) [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 87 },
     "repeat": "Instance",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(nano_node_threads{job=~'${Job}', instance=~'${Instance}'}[$__interval])",
       "legendFormat": "[ ${Instance} ] {{name}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Buckets (max over $__interval) [ ${Instance} ]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "repeat": "Instance",
     "targets": [
      {
       "expr": "max_over_time(nano_stats_objects_count{job='${Job}',instance=~'${Instance}',l1=~'election_scheduler : priority'}[$__interval])",
       "legendFormat": "[ ${Instance} ] {{l2}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Object Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "${stats_objects_l1} (size)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 71 },
     "repeat": "stats_objects_l1",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "nano_stats_objects_size{job='${Job}', instance=~'${Instance}',l1=~'${stats_objects_l1}'}",
       "legendFormat": "[ {{instance}} ] {{l2}}"
      }
     ]
    }
   ]
  },
  { "title": "Heatmap - Samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "${samples_vote_detail} (s) (over $Rate) [ ${Instance} ]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 36 },
   "repeat": "samples_vote_detail",
   "targets": [
    {
     "expr": "rate(nano_stats_samples_votes_bucket{job='${Job}', instance='${Instance}', sample='${samples_vote_detail}'}[${Rate}])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "${samples_detail} (s) (over $Rate) [ ${Instance} ]",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 54 },
   "repeat": "samples_detail",
   "targets": [
    {
     "expr": "avg_over_time(nano_stats_samples_bucket{job='${Job}',instance='${Instance}', sample='${samples_detail}'}[${Rate}])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Heatmap - Confirmation History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "collapsed": true,
   "panels": [
    {
     "title": "Confirmation History Heatmap [ Bucket ${priority_bucket} ]",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
     "repeat": "priority_bucket",
     "targets": [
      {
       "expr": "avg_over_time(nano_confirmation_history_hist_bucket{job='${Job}', type='duration' , instance='${Instance}'}[${Rate}])",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Confirmation History Heatmap [ Bucket ${priority_bucket} ]",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "avg_over_time(nano_confirmation_history_hist_bucket{job='${Job}', type='duration' , instance='${Instance}' , priority_bucket='${priority_bucket}'}[${Rate}])",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Heatmaps - Rpc response times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC ${rpc_method} duration (s)  (over $__interval)",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "repeat": "rpc_method",
     "targets": [
      {
       "expr": "sum by(le) (increase(nano_rpc_response_bucket{job='${Job}',instance=~'${Instance}',method=~'${rpc_method}'}[$__interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Version Info",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "count (nano_version_info{job='${Job}', instance=~'${Instance}'}) by (instance,build_info,network,network_identifier,node_vendor,protocol_version,rpc_version,store_vendor,store_version)",
       "legendFormat": "{{job}} {{build_info}} {{node_vendor}} {{protocol_version}} {{rpc_version}} {{store_vendor}} {{store_version}} {{network}} {{network_identifier}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Peers",
     "type": "table",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "sum(telemetry_raw_peer{job='${Job}', instance='${Instance}'}) by(job, endpoint, protocol_version)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 12, "w": 7, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "nano_node_memory_rss{job=~'${Remote}'}",
       "legendFormat": "{{job}} {{pid}} rss "
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table-old",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 7, "x": 7, "y": 22 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, job))",
       "legendFormat": "Job: {{job}}"
      }
     ]
    },
    {
     "title": "RPC Response",
     "type": "table-old",
     "description": "Method Calls are averaged over all Remotes\nRemotes are averaged over all Methods",
     "gridPos": { "h": 12, "w": 10, "x": 14, "y": 22 },
     "targets": [
      {
       "expr": "histogram_quantile(0.85, sum (rate(nano_rpc_response_bucket{job=~'${Remote}'}[5m]))by (le, method))",
       "legendFormat": "Method: {{method}}"
      }
     ]
    },
    {
     "title": "Table",
     "type": "table-old",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "max(nano_node_peers_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_online_stake_total{job=~'${Remote}'})by (job) / 1000000000000000000000000000000"
      },
      {
       "expr": "max(nano_node_database{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'} / nano_node_volume_total{job=~'${Remote}'} * 100) by (job)"
      },
      {
       "expr": "max(nano_node_volume_free{job=~'${Remote}'}) by (job)"
      },
      {
       "expr": "max(nano_node_frontier_count{job=~'${Remote}'})by (job)"
      }
     ]
    }
   ]
  }
 ]
}